require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  rubocop: warning

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe

Metrics/MethodLength:
  Max: 20

RSpec:
  Language:
    Expectations:
      - will_be_expected

RSpec/BeNil:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  CountAsOne:
     - array
     - hash
     - heredoc

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods:
    - expect

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '``'
