require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context

RSpec/ExampleLength:
  CountAsOne:
     - array
     - hash
     - heredoc

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods:
    - expect

Style/IfUnlessModifier:
  Enabled: false
