require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context

Metrics/MethodLength:
  Max: 20

RSpec/BeNil:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  CountAsOne:
     - array
     - hash
     - heredoc

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods:
    - expect

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '``'
